from __future__ import annotations

import os
from pathlib import Path


PACKAGE_ROOT = Path(__file__).resolve().parent
PROJECT_ROOT = PACKAGE_ROOT.parent.parent.parent
_pkg_spec = PACKAGE_ROOT.parent.parent / "data" / "spec_bundle"
SPEC_BUNDLE = Path(os.environ.get("ENERGY_AGENT_SPEC_BUNDLE", str(_pkg_spec)))

DEFAULT_GRID_EMISSION_FACTOR = 0.55
DEFAULT_GAS_EMISSION_FACTOR = 0.20
DEFAULT_DIESEL_EMISSION_FACTOR = 0.27
DEFAULT_THERMAL_COP = 3.5
DEFAULT_HEAT_PUMP_COP = 3.0
DEFAULT_BOILER_EFFICIENCY = 0.92
DEFAULT_PV_FULL_LOAD_HOURS = 1100
DEFAULT_WIND_CAPACITY_FACTOR = 0.26
DEFAULT_PV_NOCT_C = 45.0
DEFAULT_STANDARD_AIR_DENSITY_KG_PER_M3 = 1.225

REPORT_TITLE = "新能源电力解决方案分析报告"

MONTH_HOURS = [31 * 24, 28 * 24, 31 * 24, 30 * 24, 31 * 24, 30 * 24, 31 * 24, 31 * 24, 30 * 24, 31 * 24, 30 * 24, 31 * 24]
