from __future__ import annotations

from copy import deepcopy
from typing import Any


OUTPUT_TEMPLATE: dict[str, Any] = {
    "schema_version": "v1",
    "project_summary": {
        "project_name": "",
        "scenario_type": "",
        "scenario_detail_code": "",
        "scenario_detail_label": "",
        "operation_mode": "",
        "analysis_mode": "",
        "province": "",
        "conclusion_level": "pre_feasibility",
    },
    "applicability": {
        "pv_recommended": None,
        "wind_recommended": None,
        "storage_recommended": None,
        "microgrid_recommended": None,
        "charging_recommended": None,
        "thermal_system_recommended": None,
        "zero_carbon_factory_recommended": None,
    },
    "recommended_solution": {
        "pv_mwp": None,
        "wind_mw": None,
        "storage_power_mw": None,
        "storage_energy_mwh": None,
        "raw_storage_power_mw": None,
        "raw_storage_energy_mwh": None,
        "selected_product_power_mw": None,
        "selected_product_energy_mwh": None,
        "charging_capacity_mw": None,
        "cooling_capacity_rt": None,
        "heating_capacity_mwth": None,
        "carbon_reduction_path_summary": "",
        "grid_connection_summary": "",
        "dispatch_strategy_summary": "",
        "market_strategy_summary": "",
    },
    "alternative_solutions": [],
    "simulation_results": {
        "annual_pv_generation_mwh": None,
        "annual_wind_generation_mwh": None,
        "annual_renewable_direct_use_mwh": None,
        "annual_renewable_surplus_mwh": None,
        "annual_renewable_to_storage_mwh": None,
        "annual_renewable_to_load_mwh": None,
        "annual_grid_to_load_mwh": None,
        "annual_grid_to_storage_mwh": None,
        "annual_storage_charge_mwh": None,
        "annual_storage_discharge_mwh": None,
        "annual_charging_energy_mwh": None,
        "annual_cooling_energy_mwh": None,
        "annual_heating_energy_mwh": None,
        "annual_grid_purchase_mwh": None,
        "annual_export_mwh": None,
        "annual_curtailment_mwh": None,
        "coverage_ratio": None,
        "renewable_energy_coverage_ratio": None,
    },
    "resource_results": {
        "pv_resource_accuracy": None,
        "pv_resource_basis": None,
        "pv_p50_generation_mwh": None,
        "pv_p90_generation_mwh": None,
        "pv_effective_tilt_deg": None,
        "pv_recommended_tilt_deg": None,
        "pv_tilt_factor": None,
        "pv_azimuth_factor": None,
        "pv_tracking_factor": None,
        "pv_temperature_factor": None,
        "pv_pr_effective": None,
        "pv_lcoe_per_kwh": None,
        "wind_resource_accuracy": None,
        "wind_resource_basis": None,
        "wind_p50_generation_mwh": None,
        "wind_p90_generation_mwh": None,
        "wind_power_curve_used": None,
        "wind_mean_speed_mps": None,
        "wind_net_factor": None,
        "wind_lcoe_per_kwh": None,
    },
    "dispatch_results": {
        "baseline_peak_grid_kw": None,
        "post_storage_peak_grid_kw": None,
        "estimated_peak_reduction_kw": None,
        "daily_storage_cycles": None,
        "charging_peak_kw": None,
        "thermal_electric_peak_kw": None,
        "storage_strategy_mode": None,
        "operation_mode": "",
        "operation_mode_routing_reason": "",
        "analysis_mode": "",
        "charging_queue_index": None,
        "storage_annual_throughput_mwh": None,
        "storage_equivalent_full_cycles_per_year": None,
        "storage_power_utilization_ratio": None,
        "storage_energy_utilization_ratio": None,
        "storage_power_oversize_ratio": None,
        "storage_energy_oversize_ratio": None,
        "storage_life_years_estimate": None,
        "storage_charge_from_renewables_ratio": None,
        "storage_sizing_basis": "",
        "sizing_net_load_peak_kw": None,
        "renewable_to_storage_mwh": None,
        "renewable_to_load_mwh": None,
        "grid_to_load_mwh": None,
        "grid_to_storage_mwh": None,
        "curtailed_renewable_mwh": None,
        "storage_effective_round_trip_efficiency": None,
        "storage_reserved_soc_ratio": None,
        "storage_backup_soc_ratio": None,
        "storage_degradation_per_year": None,
        "storage_end_of_life_capacity_ratio": None,
        "daily_cycle_schedule": [],
        "monthly_storage_revenue_breakdown": [],
        "charging_diversity_factor": None,
        "thermal_annual_boiler_fuel_equivalent_mwh": None,
        "thermal_cooling_peak_kwth": None,
        "thermal_heating_peak_kwth": None,
        "charging_segment_summary": [],
    },
    "market_and_settlement": {
        "market_mode": "",
        "market_policy_mode": "",
        "price_mechanism_summary": "",
        "revenue_breakdown": [],
        "active_storage_value_model": "",
        "trading_price_spread_per_kwh": None,
        "trading_charge_benchmark_price_per_kwh": None,
        "trading_discharge_benchmark_price_per_kwh": None,
        "trading_volatility_index": None,
        "trading_best_month": "",
        "trading_worst_month": "",
        "trading_execution_summary": "",
        "trading_settlement_summary": "",
        "cooptimization_execution_summary": "",
        "spot_trading_days_covered": None,
        "spot_trading_total_cycles": None,
        "spot_trading_average_spread_yuan_per_mwh": None,
        "spot_trading_cycle_summary": "",
        "daily_spot_arbitrage_schedule": [],
        "historical_backtest_days": None,
        "historical_backtest_charge_price_avg": None,
        "historical_backtest_discharge_price_avg": None,
        "monthly_tou_policy_history": [],
        "deviation_risk_summary": "",
        "demand_charge_impact": "",
        "province_profile_status": "",
        "market_rule_notes": [],
        "profile_grid_region": "",
        "live_rule_refresh_enabled": None,
        "live_rule_refresh_status": "",
        "live_rule_last_checked_at": "",
        "live_rule_sources": [],
        "live_rule_effective_patch": {},
    },
    "design_and_interconnection": {
        "recommended_voltage_level_kv": None,
        "recommended_connection_mode": "",
        "primary_system_notes": [],
        "secondary_system_notes": [],
        "required_studies": [],
        "required_approvals": [],
    },
    "financial_results": {
        "capex_total": None,
        "opex_annual": None,
        "annual_savings_or_revenue": None,
        "annual_tax_total": None,
        "annual_income_tax": None,
        "annual_vat_and_surcharges": None,
        "annual_vat_payable": None,
        "annual_vat_surcharges_only": None,
        "initial_input_vat_credit": None,
        "tax_model": "",
        "annual_energy_charge_cost": None,
        "annual_demand_charge_cost": None,
        "annual_ancillary_service_revenue": None,
        "annual_demand_response_revenue": None,
        "annual_export_revenue": None,
        "storage_replacement_year": None,
        "storage_replacement_cost": None,
        "opex_escalation_rate": None,
        "irr": None,
        "payback_years": None,
        "npv": None,
        "lcoe": None,
        "lcos": None,
        "abatement_cost_per_tco2e": None,
    },
    "carbon_results": {
        "baseline_emissions_tco2e": None,
        "post_project_emissions_tco2e": None,
        "annual_reduction_tco2e": None,
        "scope1_reduction_tco2e": None,
        "scope2_reduction_tco2e": None,
        "scope3_reduction_tco2e": None,
        "green_power_coverage_ratio": None,
        "claim_boundary_summary": "",
        "carbon_path_breakdown": [],
    },
    "sensitivity_results": [],
    "data_quality_results": {
        "score": None,
        "level": "",
        "checks": [],
        "warnings": [],
    },
    "assumptions": [],
    "data_gaps": [],
    "risks": [],
    "confidence": {
        "level": "",
        "reason": "",
    },
}


def new_output() -> dict[str, Any]:
    return deepcopy(OUTPUT_TEMPLATE)
